upd: add iso tests

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -159,5 +159,46 @@ jobs:
         working-directory: tests/Cosmos.ilc.Tests/
         run: |
           ./output/main
+  iso-tests:
+    name: Run ISO Build Tests
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [ ubuntu-latest ]
+        dotnet-version: [ 8.0.x ]
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: ${{ matrix.dotnet-version }}
+    
+      - name: Install Xorriso
+        run: sudo apt-get update && sudo apt-get install -y xorriso
+
+      - name: Restore Dependencies
+        run: dotnet restore
+
+      - name: Build Cosmos.Patcher
+        run: dotnet build ./src/Cosmos.Patcher/Cosmos.Patcher.csproj
+
+      - name: Build Cosmos.Patcher.Build
+        run: dotnet build ./src/Cosmos.Patcher.Build/Cosmos.Patcher.Build.csproj
+
+      - name: Build Cosmos.Kernel.Tests
+        run: dotnet build ./tests/Cosmos.Kernel.Tests/Kernel.csproj --configuration Debug --no-restore --verbosity detailed
+
+      - name: Run Tests
+        run: dotnet publish -c Debug -r linux-x64 --verbosity detailed ./tests/Cosmos.Kernel.Tests/Kernel.csproj
+    
+      - name: Verify Output
+        run: | 
+          [ -f ./tests/Cosmos.Kernel.Tests/Kernel/output/Kernel.iso ] && echo "ISO exists" || (echo "ISO missing" && exit 1)
+      
+  
+    
   
 
