fix: failing test

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -184,8 +184,8 @@ jobs:
         run: dotnet restore
 
       - name: 🚀 Run Tests
-        run: dotnet publish -c Debug -r linux-x64 --verbosity detailed ./examples/KernelExample/Kernel.csproj -o ./output
+        run: dotnet publish -c Debug -r linux-x64 --verbosity detailed ./examples/KernelExample/KernelExample.csproj -o ./output
 
       - name: 🕵️‍♂️ Verify Output
         run: |
-          [ -f ./output/Kernel.iso ] && echo "ISO exists" || (echo "ISO missing" && exit 1)
+          [ -f ./output/KernelExample.iso ] && echo "ISO exists" || (echo "ISO missing" && exit 1)
