Feature/ilc tests (#47)
* add: ilc tests

* fix: force make to build Liquip.ilc.Tests

* fix: failing test

* fix: failing test

* fix: failing test

* fix: faling test

* upd: improve globbing

* upd: add debugging in ci

* upd: add additional debugging

* upd: action ci

* upd: clean up debug

* fix: format ci

* upd: dependencies

* upd: switch dependencies

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -25,6 +25,5 @@ jobs:
         run: dotnet restore
 
       - name: Check Formatting
-        run: |
-          dotnet format --verify-no-changes --severity error || echo "::error file=Code Formatting::Some files need formatting. Run 'dotnet format' locally."
+        run: dotnet format --verify-no-changes --severity error || { echo "::error file=Code Formatting::Some files need formatting. Run 'dotnet format' locally."; exit 1; }
 
